### PR TITLE
add pagination

### PR DESCRIPTION
**Pull request by Fcmam5**
I added the pagination, but I'm having an issue with pages beyond the first one, I spent many hours Googling & trying different StackOverFlow solutions ... But I still have the same issue.

### CODE REVIEW

**Comment by cacarrara** [comment]
CI is failing here.

**Comment by cacarrara** [comment]
I do not get why you change form to add pagination. 🤔

**Comment by Pal0r** [comment]
@Fcmam5 You were pretty close. I used a bit of your view logic in [PR #29 ](https://github.com/mochaoss/inspace/pull/29)

**Comment by cacarrara** [comment]
It's being done in #29

**Pull request closed without merging**
